### ISSUE TITLE
typographical errors || grammar/syntax errors

### ISSUE THREAD

**Issue by mouthbreathingretard** [udacity/frontend-nanodegree-arcade-game#3]
[resources.js line 2](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/resources.js#L2)

```
This is simple an image loading utility.
```

simply

---

[resources.js lines 39&ndash;42](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/resources.js#L39)

```
/* If this URL has been previously loaded it will exist within
 * our resourceCache array. Just return that image rather
 * re-loading the image.
 */
```

rather than

---

[resources.js line 73](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/resources.js#L73)

```
This is used by developer's to
```

developers

---

[resources.js line 81&ndash;82](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/resources.js#L73)

```
/* This function determines if all of the images that have been requested
 * for loading have in fact been completed loaded.
```

completely

---

[engine.js lines 18&ndash;20](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/engine.js#L18)

```
set the canvas elements height/width and add it to the DOM.
```

element's

---

[engine.js line 86](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/engine.js#L86)

```
This is called by the update function  and loops
```

one space

---

[engine.js line 90](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/engine.js#L90)

```
the data/properties related to  the object. Do your drawing in your
```

one space

---

[engine.js line 144](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/engine.js#L144)

```
It's purpose is
```

Its

---

[engine.js line 180](https://github.com/udacity/frontend-nanodegree-arcade-game/blob/3d1597d2fb23dd7b71b3fd61c91ac0ef5551e339/js/engine.js#L180)

```
so that developer's can use it
```

developers

---

**Comment by hbkwong** [comment]
All fixed!
