### ISSUE TITLE
ReferenceError: allEnemies is not defined

### ISSUE THREAD

**Issue by MrFoldAnyTen** [udacity/frontend-nanodegree-arcade-game#48]
THe page index.html does not show anything to start.
ReferenceError: allEnemies is not defined

**Comment by vtechmonkey** [comment]
you need to create the empty array for allEnemies and create at least one enemy and have it pushed to that array.

**Comment by cherimarie** [comment]
In the Getting Started section of guide, it says "index.html - opening index.html should load the game". If we don't expect game to load properly until some code is changed, perhaps that part of the guide should be updated to say so. It's no fun to start a project confused.
