### ISSUE TITLE
Authentication failed...!!!

### ISSUE THREAD

**Issue by mahmmad3007** [udacity/frontend-nanodegree-arcade-game#93]
Hi,

I'm trying to push my code to the repository but i get this message:

"
Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.
"
I checked my username password, everything seems OK to me...
Any help?

**Comment by guti7** [comment]
Make sure you are pushing to your own copy of the repository located on your account, and not the original(upstream) from udacity.
